//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nimap_Machine_Test.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Nimap_MVC_Machine_TestEntities : DbContext
    {
        public Nimap_MVC_Machine_TestEntities()
            : base("name=Nimap_MVC_Machine_TestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblCategory> tblCategories { get; set; }
        public virtual DbSet<tblProduct> tblProducts { get; set; }
    
        public virtual ObjectResult<sp_join_Result> sp_join()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_join_Result>("sp_join");
        }
    }
}
