//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nimap_Machine_Test.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int Product_id { get; set; }
        public string Product_Name { get; set; }
        public Nullable<int> Category_id { get; set; }
    
        public virtual tblProduct tblProduct1 { get; set; }
        public virtual tblProduct tblProduct2 { get; set; }
        public virtual tblCategory tblCategory { get; set; }
    }
}
